language: node_js
node_js:
  - "stable"
dist: trusty
cache:
  directories:
  - node_modules
before_script:
  - yarn
after_success:
  - yarn netlify:deploy
after_failure:
  - echo "failed ya z3eem"
script:
  - yarn lint
  - yarn test
  - yarn build
deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_AUTH_TOKEN
