language: node_js
node_js:
  - "stable"
dist: trusty
cache:
  directories:
  - node_modules
before_script:
  - yarn
after_success:
  - yarn netlify:deploy
script:
  - yarn lint
  - yarn test
  - yarn build
